import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LargeSizeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
          
             <div className="mt-8 mb-4 px-2 lg:w-[calc(100vw-250px)]">
              {children}
             </div>
    
    
  );
}
