import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LeftSideBar from "@/components/layout/LeftSideBar";
import TopSideBar from "@/components/layout/TopSideBar";
import MobileSideBar from "@/components/layout/MobileSideBar";
import TanstackProvider from "@/utils/TanstackProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="max-w-[1536px] mx-auto">
          <div className="flex items-center">
            <TanstackProvider>
            <div className="grid lg:grid-flow-col  ">
              <MobileSideBar/>
              <TopSideBar/>
              <LeftSideBar />
              <div className="">               
              {children}
              </div>
            </div>
            </TanstackProvider>
          </div>

          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
